//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRental.Models
{
    using System;
    
    public enum CarType : int
    {
        Small = 1,
        Compact = 2,
        Sedan = 3,
        Limousine = 4,
        Monovolume = 5,
        SUV = 6
    }
}
